### PR TITLE
Improve UX for search-admin

### PR DESCRIPTION
**Pull request by tijmenb**
General tidying-up of the interface.

- Improve layout of query list view (together with @tarastockford)
- Add correct page `<titles>` and `<h1>` tags for all pages
- Add breadcrumbs for all pages
- Make the navigation bar look `active`
- Make all forms bootstrap-styled
- Respect admin styleguide (specifically `btn-success` for save)
- Put buttons in right place

### Trello tickets:

https://trello.com/c/3FqslLiL/86-search-admin-show-comment-fields-on-list-page

### Before / after

before

after

### CODE REVIEW

**Comment by fofr** [comment]
This looks excellent. It'd be nice to see some screenshots of the other major changes, eg form updates.

I have some minor comments:
* The vertical alignment of the query cell looks odd when there's only a single bet. Leaving the query aligned to the top for all rows should work fine as the table has enough visual queues to associate it with the other data in the row.
* Did you consider dropping the new comment to a new line, beneath the slug?
* What's the benefit of merging the match type into the query column?

**Comment by fofr** [comment]
Where "Worst bets" are included in the bets column looks slightly odd:
screen shot 2015-05-11 at 13 24 41

Could some icons help here so the slugs could be presented as an uninterrupted list? Perhaps +/- glyphicons?

A quick mockup of what I was thinking, though not quite right:
screen shot 2015-05-11 at 13 28 57

**Comment by tijmenb** [comment]
@fofr 

Updated with your feedback, thanks a lot!

> - The vertical alignment of the query cell looks odd [...]

Agreed, updated.

> - Did you consider dropping the new comment to a new line, beneath the slug?

Does indeed look better.

> - What's the benefit of merging the match type into the query column?

When the bets were in separate columns they looked better that way, but that doesn't make sense now. 

### New after

screen shot 2015-05-11 at 16 43 43

- Bets link to the bet edit page
- Match type isn't linked anymore to prevent confusion about where it would link
- Filter table header also updated.

### Forms

> It'd be nice to see some screenshots of the other major changes, eg form updates

Before:

before

After:

after

**Comment by fofr** [comment]
:+1: Good stuff. I also like that the query is no longer in quotes.

**Pull request merged**
