### PR TITLE
External link url must contain a host

### PR DESCRIPTION
**Pull request by dwhenry**
While the url `http:/path-to-page` is a valida URL it is not
valid for our purpose as we require the host that we are redirecting
to.

https://trello.com/c/nQfP94ph/312-search-admin-url-validation-in-search-admin-breaks-if-theres-only-one-slash

### CODE REVIEW

**Comment by Rosa-Fox** [comment]
Hi,

Looks good. Could be good to add more feedback to the user?

Maybe something along the lines of 

```
uri.is_a?(URI::HTTP) && uri.host.present?
record.errors[attribute] << "host (i.e www.example.com) not present" if !uri.host.present?
```

Though probably a neater way of doing it..?

**Comment by dwhenry** [comment]
@Rosa-Fox took a bit of effort but think this might be nicer.

**Comment by Rosa-Fox** [comment]
It is still falling through to 'invalid url' if the host is not valid.

```
[1] pry(#<UrlValidator>)> value
=> "http:/path-not-host"
[2] pry(#<UrlValidator>)> uri = parse(value)
=> #<URI::HTTP http:/path-not-host>
[3] pry(#<UrlValidator>)> unless uri&.host
[3] pry(#<UrlValidator>)*   msg = options[:message] || (uri ? "is an invalid URL" : "does not have a valid host")
[3] pry(#<UrlValidator>)*   record.errors[attribute] << msg
[3] pry(#<UrlValidator>)* end
=> ["is an invalid URL"]
```
Briefly tried to figure out a solution, but will continue tomorrow!

**Comment by dwhenry** [comment]
@Rosa-Fox had the logic the wrong way around, this has now been fixed and the tests improved

**Pull request merged**
